### ISSUE TITLE
How to you install it ?

### ISSUE THREAD

**Issue by benjaminMatteJean** [hazyuun/Chrono#6]
How do you install this library ? There are no steps in the README describing how to install it. 

Thanks, it seems promising

**Comment by hazyuun** [comment]
Hello ! Thank you so much for your feedback, I appreciate it !

I am adding a "How to install" section to the README file

Have a nice day/night !

**Comment by hazyuun** [comment]
I added it, you can check the updated README file now.

**Comment by hazyuun** [comment]
I'm closing this since it's been inactive for a while, feel free to open an issue if there is anything else.

Thanks again for your feedback !
